# Pytorch basic

In [2]:
import torch




In [3]:
x = torch.arange(12, dtype=torch.float32)
print(x)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])


In [4]:
x = torch.reshape(x, (3, 4)) 
print(x.size()) 


torch.Size([3, 4])


In [5]:
x.size()


torch.Size([3, 4])

In [6]:
torch.randn(3, 4)  
torch.rand(2, 3, 2) 


tensor([[[0.8016, 0.6886],
         [0.6971, 0.4457],
         [0.5036, 0.8734]],

        [[0.7798, 0.0240],
         [0.2618, 0.5790],
         [0.6899, 0.6044]]])

In [7]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

# Data Indexing and Slicing

In [8]:
x[1,2]= 100
print(x)

tensor([[  0.,   1.,   2.,   3.],
        [  4.,   5., 100.,   7.],
        [  8.,   9.,  10.,  11.]])


In [9]:
print(x[-1, -1])  

tensor(11.)


In [10]:
x[:2 , :] = 12
print(x)

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


# Operation

In [11]:
x.reshape(3, 4)  # This is another way to reshape the tensor
x = x.reshape(3, 4)  # Reshape the tensor to 3 rows and 4 columns
print(x)



tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


# Operation

In [13]:
y = torch.exp(x)
print(y)

tensor([[162754.7969, 162754.7969, 162754.7969, 162754.7969],
        [162754.7969, 162754.7969, 162754.7969, 162754.7969],
        [  2980.9580,   8103.0840,  22026.4648,  59874.1406]])


In [22]:
y.reshape(6,2)
print(y)

tensor([[162754.7969, 162754.7969, 162754.7969, 162754.7969],
        [162754.7969, 162754.7969, 162754.7969, 162754.7969],
        [  2980.9580,   8103.0840,  22026.4648,  59874.1406]])


In [28]:
x = torch.arange(12, dtype = torch.float32 ).reshape(3,4)  
y = torch.tensor([[1,2,3,4] , [1,2,3,4] , [4,3,2,1]])
torch.cat((x,y))
torch.cat((x,y) , dim = 1)

tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  4.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])